In [1]:
import streamlit as st
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import cross_val_score,train_test_split
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor,AdaBoostRegressor
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.neighbors import KNeighborsRegressor
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
import warnings
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_csv('https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv')
data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
Sex_encoder= LabelEncoder()
Smoker_encoder= LabelEncoder()
Region_encoder= LabelEncoder()

In [4]:
data["Sex"] = Sex_encoder.fit_transform(data.sex)
data["Smoker"] = Smoker_encoder.fit_transform(data.smoker)
data["Region"] = Region_encoder.fit_transform(data.region)
data.head()

,age,sex,bmi,children,smoker,region,charges,Sex,Smoker,Region
0,19,female,27.900,0,yes,southwest,16884.92400,0,1,3
1,18,male,33.770,1,no,southeast,1725.55230,1,0,2
2,28,male,33.000,3,no,southeast,4449.46200,1,0,2
3,33,male,22.705,0,no,northwest,21984.47061,1,0,1
4,32,male,28.880,0,no,northwest,3866.85520,1,0,1

In [5]:
X= data[['age', 'Sex', 'bmi', 'children',  'Smoker','Region']].values
X

array([[19.  ,  0.  , 27.9 ,  0.  ,  1.  ,  3.  ],
       [18.  ,  1.  , 33.77,  1.  ,  0.  ,  2.  ],
       [28.  ,  1.  , 33.  ,  3.  ,  0.  ,  2.  ],
       ...,
       [18.  ,  0.  , 36.85,  0.  ,  0.  ,  2.  ],
       [21.  ,  0.  , 25.8 ,  0.  ,  0.  ,  3.  ],
       [61.  ,  0.  , 29.07,  0.  ,  1.  ,  1.  ]], shape=(1338, 6))

In [6]:
Y = data[["charges"]].values
Y

array([[16884.924 ],
       [ 1725.5523],
       [ 4449.462 ],
       ...,
       [ 1629.8335],
       [ 2007.945 ],
       [29141.3603]], shape=(1338, 1))

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [8]:
model = Sequential()

In [9]:
model.add(Input(shape =  (X_train.shape[1],)))
model.add(Dense(15, activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(120, activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(100, activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(80, activation = 'relu'))
model.add(Dense(1, activation = 'relu'))

In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 15)             │           105 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 15)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 120)            │         1,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 120)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 100)            │        12,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 80)             │         8,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            81 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 22,286 (87.05 KB)

 Trainable params: 22,286 (87.05 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.compile(optimizer= 'adam', loss= "mean_squared_error")

In [12]:
X_train.shape

(1070, 6)

In [13]:
model.fit(X_train, y_train, batch_size=10, epochs=10, validation_data= (X_test, y_test), callbacks=EarlyStopping(patience=5))

Epoch 1/10
107/107 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 258101408.0000 - val_loss: 141873968.0000
Epoch 2/10
107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 138128688.0000 - val_loss: 132213560.0000
Epoch 3/10
107/107 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 137268176.0000 - val_loss: 132135680.0000
Epoch 4/10
107/107 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 135771808.0000 - val_loss: 131301608.0000
Epoch 5/10
107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 134038960.0000 - val_loss: 129864096.0000
Epoch 6/10
107/107 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 134605376.0000 - val_loss: 130361768.0000
Epoch 7/10
107/107 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 133087816.0000 - val_loss: 129805128.0000
Epoch 8/10
107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 133481152.0000 - val_loss: 128196256.0000
Epoch 9/10
107/107 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 131549184.0000 - val_loss: 127149176.0000
Epoch 10/10
107/107 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 128467752.0000 - val_loss: 126388240.0000

In [14]:
pred = model.predict(X_test)
pred

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

array([[14674.362 ],
       [13074.907 ],
       [19626.121 ],
       [15243.185 ],
       [11117.187 ],
       [15170.365 ],
       [ 8174.3394],
       [20618.744 ],
       [ 9241.69  ],
       [16397.992 ],
       [12397.202 ],
       [14811.462 ],
       [11634.99  ],
       [19115.9   ],
       [21204.467 ],
       [18500.762 ],
       [18382.11  ],
       [17709.297 ],
       [14935.6455],
       [15057.808 ],
       [10630.776 ],
       [15351.609 ],
       [ 9576.792 ],
       [12124.257 ],
       [16339.96  ],
       [17512.191 ],
       [18848.783 ],
       [11892.36  ],
       [15351.749 ],
       [ 9438.496 ],
       [14368.626 ],
       [17886.3   ],
       [10771.194 ],
       [10618.175 ],
       [11141.795 ],
       [17021.893 ],
       [ 9282.3545],
       [14496.702 ],
       [16739.617 ],
       [15326.254 ],
       [10097.951 ],
       [10790.999 ],
       [18309.836 ],
       [17425.465 ],
       [13963.798 ],
       [17712.145 ],
       [11054.302 ],
       [10130.799 ],
       [17327.074 ],
       [14036.867 ],
       [19828.893 ],
       [ 9495.698 ],
       [16198.755 ],
       [ 8913.179 ],
       [18167.629 ],
       [17127.508 ],
       [11280.599 ],
       [14661.294 ],
       [18072.021 ],
       [17395.996 ],
       [18934.982 ],
       [14543.926 ],
       [20016.441 ],
       [13868.339 ],
       [16768.066 ],
       [10867.683 ],
       [10972.386 ],
       [16531.844 ],
       [ 9618.044 ],
       [11893.276 ],
       [15265.954 ],
       [16128.582 ],
       [16084.247 ],
       [14580.0625],
       [16463.008 ],
       [12942.231 ],
       [12571.975 ],
       [16628.264 ],
       [12260.909 ],
       [14594.985 ],
       [10441.085 ],
       [19457.166 ],
       [12385.41  ],
       [13176.295 ],
       [15705.476 ],
       [17719.83  ],
       [12778.63  ],
       [17790.164 ],
       [15080.304 ],
       [18387.812 ],
       [20576.3   ],
       [18846.105 ],
       [16112.722 ],
       [12295.112 ],
       [14803.312 ],
       [14860.313 ],
       [13349.412 ],
       [10218.276 ],
       [12320.925 ],
       [12224.987 ],
       [11735.77  ],
       [ 9134.347 ],
       [16040.3955],
       [18940.367 ],
       [17687.777 ],
       [10595.8955],
       [15344.194 ],
       [16263.092 ],
       [ 8054.5522],
       [16621.51  ],
       [10084.574 ],
       [14332.916 ],
       [18526.504 ],
       [14371.859 ],
       [16306.458 ],
       [10468.501 ],
       [18296.836 ],
       [15182.938 ],
       [13714.948 ],
       [10260.718 ],
       [13570.325 ],
       [15454.05  ],
       [18481.945 ],
       [11723.519 ],
       [10687.712 ],
       [15077.536 ],
       [15643.948 ],
       [16312.962 ],
       [18775.57  ],
       [12659.251 ],
       [11930.546 ],
       [14318.032 ],
       [14233.733 ],
       [16576.115 ],
       [13980.329 ],
       [19353.795 ],
       [13693.874 ],
       [15322.341 ],
       [17420.045 ],
       [14588.054 ],
       [12508.038 ],
       [17081.068 ],
       [12050.134 ],
       [18206.77  ],
       [10060.0625],
       [16459.51  ],
       [12556.98  ],
       [11642.856 ],
       [17997.46  ],
       [13097.528 ],
       [19552.152 ],
       [10033.911 ],
       [11518.592 ],
       [14439.763 ],
       [15628.046 ],
       [13796.735 ],
       [19323.227 ],
       [15380.256 ],
       [11066.587 ],
       [15950.269 ],
       [18629.355 ],
       [ 8974.984 ],
       [18688.645 ],
       [ 9649.612 ],
       [11430.212 ],
       [16087.788 ],
       [20992.74  ],
       [18816.21  ],
       [16549.857 ],
       [10622.532 ],
       [14313.293 ],
       [14127.577 ],
       [16298.231 ],
       [11660.374 ],
       [ 9413.413 ],
       [15913.945 ],
       [10109.788 ],
       [20940.832 ],
       [11508.368 ],
       [16433.086 ],
       [19678.047 ],
       [ 7861.3135],
       [14013.647 ],
       [13312.424 ],
       [11157.128 ],
       [11206.238 ],
       [12039.245 ],
       [11179.228 ],
       [18250.602 ],
       [16916.777 ],
       [12247.679 ],
       [ 9319.374 ],
       [ 9030.567 ],
       [14581.607 ],
       [20223.639 ],
       [16862.727 ],
       [ 8746.496 ],
       [17258.781 ],
       [ 8785.38  ],
       [15054.868 ],
       [ 9571.847 ],
       [17254.207 ],
       [14910.215 ],
       [ 9622.523 ],
       [10311.388 ],
       [11175.761 ],
       [15616.32  ],
       [ 9179.734 ],
       [17476.371 ],
       [ 9081.486 ],
       [17148.316 ],
       [16639.348 ],
       [18983.7   ],
       [11558.471 ],
       [13486.278 ],
       [11560.562 ],
       [12219.566 ],
       [18121.008 ],
       [17188.047 ],
       [13725.388 ],
       [11043.1455],
       [16644.146 ],
       [16980.027 ],
       [17506.545 ],
       [10728.778 ],
       [12817.909 ],
       [ 7597.172 ],
       [ 9837.228 ],
       [16528.404 ],
       [18572.664 ],
       [11303.748 ],
       [14261.923 ],
       [10808.9375],
       [15149.509 ],
       [14528.466 ],
       [17091.434 ],
       [11732.302 ],
       [15009.964 ],
       [17553.074 ],
       [10927.429 ],
       [16409.623 ],
       [14021.101 ],
       [11622.797 ],
       [11076.023 ],
       [ 8828.259 ],
       [11359.286 ],
       [11135.471 ],
       [12657.586 ],
       [20370.09  ],
       [ 7417.269 ],
       [ 9467.628 ],
       [15418.983 ],
       [10416.56  ],
       [16401.258 ],
       [10109.962 ],
       [11295.573 ],
       [17965.867 ],
       [12087.843 ],
       [14872.317 ],
       [12854.177 ],
       [14294.102 ],
       [16958.943 ],
       [12148.039 ],
       [20834.656 ],
       [17320.367 ],
       [13636.968 ],
       [20930.957 ],
       [16958.848 ]], dtype=float32)

In [15]:
history = model.history

In [16]:
history.history

{'loss': [258101408.0,
  138128688.0,
  137268176.0,
  135771808.0,
  134038960.0,
  134605376.0,
  133087816.0,
  133481152.0,
  131549184.0,
  128467752.0],
 'val_loss': [141873968.0,
  132213560.0,
  132135680.0,
  131301608.0,
  129864096.0,
  130361768.0,
  129805128.0,
  128196256.0,
  127149176.0,
  126388240.0]}

In [17]:
plt.plot(history.history["loss"])
plt.plot(history.history["val_loss"])
plt.show()